---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: xelon-csi-node-driver-registrar-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: xelon-csi-node-driver-registrar-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Values.node.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: xelon-csi-node-driver-registrar-role
  apiGroup: rbac.authorization.k8s.io
