{{- if .Values.xelonSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: xelon-api-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  baseUrl: {{ .Values.xelonSecret.baseUrl | quote }}
  clientId: {{ .Values.xelonSecret.clientId | quote }}
  cloudId: {{ .Values.xelonSecret.cloudId | quote }}
  kubernetesClusterId: {{ .Values.xelonSecret.kubernetesClusterId | quote }}
  token: {{ .Values.xelonSecret.token | quote }}
{{- end -}}
