linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused
    - vet

linters-settings:
  goimports:
    local-prefixes: github.com/Xelon-AG/xelon-csi

output:
  format: tab

run:
  deadline: 10m
