name: Tests
on:
  pull_request:
    paths-ignore:
      - "CHANGELOG.md"
      - "README.md"
  push:
    branches: [main]
    paths-ignore:
      - "CHANGELOG.md"
      - "README.md"

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Build driver
        run: make build

  unit-tests:
    name: unit tests
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Install tools
        run: make tools

      - name: Lint source code
        run: make lint

      - name: Run unit tests
        run: make test
